// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

type Item struct {
	ID          int64          `json:"id"`
	Description sql.NullString `json:"description"`
	Amount      int64          `json:"amount"`
	Likes       int64          `json:"likes"`
	CreatedAt   time.Time      `json:"created_at"`
}
