// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	GetItem(ctx context.Context, id int64) (Item, error)
	ListItems(ctx context.Context) ([]Item, error)
}

var _ Querier = (*Queries)(nil)
