version: '3'

services:
  postgres:
    image: 'postgres'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e_commerce
    volumes: 
      - ../db_data/postgres/:/var/lib/postgresql/data
  
  redis:
    image: 'redis'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ../db_data/redis/:/data
    